version: '2.1'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 10s
      timeout: 10s
      retries: 3
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    healthcheck:
      test: "kafka-topics.sh --zookeeper zookeeper:2181 --list 2>&1 | grep \"topology\""
      interval: 3s
      timeout: 10s
      retries: 5
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: INSIDE_DOCKER://:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE_DOCKER://kafka:9092
      #KAFKA_ADVERTISED_LISTENERS: OUTSIDE_DOCKER://${DOCKER_HOST_IP:-127.0.0.1}:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE_DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE_DOCKER
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "customers:1:1,transactions:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  sim-customer-acquisition:
    build: sim-customer-acquisition
    environment:
      APP_KAFKA_BROKERS: kafka:9092
      APP_SERVER_PORT: 8080
    depends_on:
      kafka:
        condition: service_started
    ports: 
      - "8080:8080"
